### ISSUE TITLE
Share volume

### ISSUE THREAD

**Issue by latermonk** [latermonk/Navigation-Pannel#4]
在 Kubernetes 中，可以通过多种方式将文件挂载到容器的 `/tmp` 目录。以下是使用 `Secret`、`emptyDir` 和 `initContainer` 来实现这一目标的步骤：

### 1. 使用 `Secret` 挂载文件
`Secret` 通常用于存储敏感信息，但也可以用于挂载普通文件。

#### 1.1 创建 Secret
首先，创建一个包含文件的 `Secret`：

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  my-file.txt: <base64-encoded-file-content>
```

将文件内容进行 Base64 编码：

```bash
cat my-file.txt | base64
```

#### 1.2 在 Pod 中挂载 Secret
然后在 Pod 中挂载这个 `Secret`：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/my-file.txt
      subPath: my-file.txt
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
```

### 2. 使用 `emptyDir` 挂载文件
`emptyDir` 是一个临时目录，可以在 Pod 的生命周期内共享数据。

#### 2.1 在 Pod 中挂载 `emptyDir`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: temp-volume
      mountPath: /tmp
  volumes:
  - name: temp-volume
    emptyDir: {}
```

### 3. 使用 `initContainer` 和 `emptyDir` 拷贝文件
`initContainer` 可以在主容器启动之前执行一些任务，比如将文件拷贝到共享的 `emptyDir` 中。

#### 3.1 在 Pod 中使用 `initContainer`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello, World!" > /mnt/my-file.txt']
    volumeMounts:
    - name: temp-volume
      mountPath: /mnt
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: temp-volume
      mountPath: /tmp
  volumes:
  - name: temp-volume
    emptyDir: {}
```

### 4. 综合使用 `Secret`、`emptyDir` 和 `initContainer`
你可以结合使用 `Secret`、`emptyDir` 和 `initContainer` 来实现更复杂的文件拷贝操作。

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'cp /mnt-secret/my-file.txt /mnt-empty/my-file.txt']
    volumeMounts:
    - name: secret-volume
      mountPath: /mnt-secret
    - name: temp-volume
      mountPath: /mnt-empty
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: temp-volume
      mountPath: /tmp
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  - name: temp-volume
    emptyDir: {}
```

### 总结
- **Secret**：适合挂载敏感信息或配置文件。
- **emptyDir**：适合临时存储和共享数据。
- **initContainer**：适合在主容器启动前执行一些初始化任务。

通过结合这些方法，你可以灵活地将文件挂载到容器的 `/tmp` 目录中。
